version: '3.8'

services:
  streamlit-app:
    build: . # Build the image from the Dockerfile in the current directory
    container_name: pyaedt_streamlit_app
    network_mode: host # Use the host's network stack
    env_file:
      - .env
    # Override the default command to correctly substitute the port
    command: ["streamlit", "run", "src/streamlit_app.py", "--server.port=${PORT}", "--server.address=0.0.0.0"]
