version: '3.8'

services:
  streamlit-app:
    build: . # Build the image from the Dockerfile in the current directory
    container_name: pyaedt_streamlit_app
    ports:
      - "8080:8080" # Map host port 8080 to container port 8080
    network_mode: host # Use the host's network stack
    environment:
      - PORT=8080
      