version: '3.8'

services:
  streamlit-app:
    build: . # Build the image from the Dockerfile in the current directory
    container_name: pyaedt_streamlit_app
    network_mode: host # Use the host's network stack
    environment:
      - PORT=8080
      